imports:
    - { resource: './services/' }

services:
    AppBundle\Event\SymfonyEventHandler:
        autowire: true
        public: false
        class: AppBundle\Event\SymfonyEventHandler
        arguments:
            - "@event_dispatcher"
