imports:
    - { resource: './services/' }

services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    _instanceof:
        Symfony\Component\Serializer\Normalizer\NormalizerInterface:
            tags: ["serializer.normalizer"]

    AppBundle\Event\SymfonyEventHandler: ~

    Manuel\LocalBank\Event\EventHandler: '@AppBundle\Event\SymfonyEventHandler'

    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Manuel\Http\EventListener\:
        public: true
        resource: '../../src/Manuel/Http/EventListener'