Manuel\LocalBank\Account\Account:
    type: entity
    repositoryClass: AppBundle\Repository\AccountRepository
    embedded:
        accountId:
            class: Manuel\LocalBank\ValueObject\EntityId
            columnPrefix: false
        balance:
            class: Manuel\LocalBank\ValueObject\Money
    fields:
        locked:
            type: boolean

    manyToOne:
        client:
            targetEntity: Manuel\LocalBank\Account\Client\Client
            idaa: 1

