Manuel\LocalBank\Account\Client\Client:
    type: entity
    repositoryClass: AppBundle\Repository\ClientRepository
    embedded:
        id:
            class: Manuel\LocalBank\ValueObject\EntityId
            columnPrefix: false
        email:
            class: Manuel\LocalBank\ValueObject\Email
        address:
            class: Manuel\LocalBank\ValueObject\Address