services:
    _defaults:
        autowire: true
        autoconfigure: true

    Manuel\LocalBank\Account\Service\:
        resource: '../../../src/Manuel/LocalBank/Account/Service/'

    Manuel\LocalBank\Application\Service\:
        resource: '../../../src/Manuel/LocalBank/Application/Service/*/*Service'
        public: true

    Manuel\LocalBank\Application\Service\CreateAccount\CreateAccountService:
        public: true

    Manuel\LocalBank\Application\Service\EditAccount\EditAccountService:
        public: true
