services:
#    _defaults:
#        autowire: true
#        public: false
#        autoconfigure: true

    Doctrine\ORM\EntityRepository:
        abstract: true
        factory: ["@doctrine.orm.entity_manager", "getRepository"]

    AppBundle\Repository\AccountRepository:
        arguments: [Manuel\LocalBank\Account\Account]
        parent: Doctrine\ORM\EntityRepository

    AppBundle\Repository\ClientRepository:
        arguments: [Manuel\LocalBank\Account\Client\Client]
        parent: Doctrine\ORM\EntityRepository

    AppBundle\Repository\TransactionRepository:
        arguments: [Manuel\LocalBank\Account\Operation\Transaction]
        parent: Doctrine\ORM\EntityRepository
